name: Discord Changelog Notification

on:
  push:
    branches: [ main ]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Send Discord notification
      run: |
        curl -H "Content-Type: application/json" \
        -d '{
          "username": "GitBot",
          "content": "📝 **New Commit:** ${{ github.event.head_commit.message }}"
        }' \
        ${{ secrets.DISCORD_WEBHOOK }}
