name: Discord Changelog Notification
on:
  push:
    branches: ["main"]
jobs:
  discord-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          nodetail: true
          content: ":pencil: **New Commit**"
          title: ""
          description: ${{ github.event.head_commit.message }}
          color: 0x7289DA
          username: Nova Updates
          footer: ":pencil: Changelog :pencil:"
